# Generated by Django 3.1.6 on 2021-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival_time', '0002_auto_20210506_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tracking',
            field=models.ManyToManyField(related_name='tracked_stations', to='arrival_time.Station'),
        ),
    ]
