# Generated by Django 3.1.6 on 2021-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival_time', '0003_auto_20210507_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date_created',
        ),
    ]
