# Generated by Django 3.1.6 on 2021-05-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival_time', '0004_auto_20210507_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Station',
            new_name='Stop',
        ),
    ]
