# Generated by Django 3.1.6 on 2021-05-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival_time', '0005_auto_20210507_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='station',
            new_name='stop',
        ),
    ]
